server:
  port: 8088

dubbo:
  application:
    name: qf-v1-user-service
  registry:
    protocol: zookeeper
    address: 192.168.171.134:2181
  protocol:
    port: 28008
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v1
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.171.134
    port: 6379
    jedis:
      pool:
        max-active: 20
    password: panxy

