package com.qf.v1.entity;

import java.io.Serializable;
import java.util.Date;

public class TProduct implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.id
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.name
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.image
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.price
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.sale_price
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private Long salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.sale_point
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private String salePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.type_id
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.type_name
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.flag
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private Boolean flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.create_time
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.update_time
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.create_user
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.update_user
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    private Long updateUser;

    private String productDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.id
     *
     * @return the value of t_product.id
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.id
     *
     * @param id the value for t_product.id
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.name
     *
     * @return the value of t_product.name
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.name
     *
     * @param name the value for t_product.name
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.image
     *
     * @return the value of t_product.image
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.image
     *
     * @param image the value for t_product.image
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.price
     *
     * @return the value of t_product.price
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.price
     *
     * @param price the value for t_product.price
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.sale_price
     *
     * @return the value of t_product.sale_price
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public Long getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.sale_price
     *
     * @param salePrice the value for t_product.sale_price
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.sale_point
     *
     * @return the value of t_product.sale_point
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public String getSalePoint() {
        return salePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.sale_point
     *
     * @param salePoint the value for t_product.sale_point
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setSalePoint(String salePoint) {
        this.salePoint = salePoint == null ? null : salePoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.type_id
     *
     * @return the value of t_product.type_id
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.type_id
     *
     * @param typeId the value for t_product.type_id
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.type_name
     *
     * @return the value of t_product.type_name
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.type_name
     *
     * @param typeName the value for t_product.type_name
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.flag
     *
     * @return the value of t_product.flag
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.flag
     *
     * @param flag the value for t_product.flag
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.create_time
     *
     * @return the value of t_product.create_time
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.create_time
     *
     * @param createTime the value for t_product.create_time
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.update_time
     *
     * @return the value of t_product.update_time
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.update_time
     *
     * @param updateTime the value for t_product.update_time
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.create_user
     *
     * @return the value of t_product.create_user
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.create_user
     *
     * @param createUser the value for t_product.create_user
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.update_user
     *
     * @return the value of t_product.update_user
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.update_user
     *
     * @param updateUser the value for t_product.update_user
     *
     * @mbggenerated Wed Dec 26 12:09:00 CST 2018
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }


    @Override
    public String toString() {
        return "TProduct{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", image='" + image + '\'' +
                ", price=" + price +
                ", salePrice=" + salePrice +
                ", salePoint='" + salePoint + '\'' +
                ", typeId=" + typeId +
                ", typeName='" + typeName + '\'' +
                ", flag=" + flag +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", createUser=" + createUser +
                ", updateUser=" + updateUser +
                ", productDesc='" + productDesc + '\'' +
                '}';
    }
}