package com.qf.v1.mapper;


import com.qf.v1.common.base.IBaseDao;
import com.qf.v1.entity.TProductType;

public interface TProductTypeMapper extends IBaseDao<TProductType>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Wed Dec 26 12:09:24 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Wed Dec 26 12:09:24 CST 2018
     */
    int insert(TProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Wed Dec 26 12:09:24 CST 2018
     */
    int insertSelective(TProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Wed Dec 26 12:09:24 CST 2018
     */
    TProductType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Wed Dec 26 12:09:24 CST 2018
     */
    int updateByPrimaryKeySelective(TProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Wed Dec 26 12:09:24 CST 2018
     */
    int updateByPrimaryKey(TProductType record);
}