spring:
  data:
    solr:
      host: http://192.168.171.134:8089/solr
  datasource:
      url: jdbc:mysql://localhost:3306/qf-v1
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.171.134
    virtual-host: /java1807
    username: panxy
    password: pan19950208
    port: 5672

dubbo:
  application:
    name: qf-v1-search-service
  registry:
    protocol: zookeeper
    address: 192.168.171.134:2181
  protocol:
    port: 28002
server:
  port: 8081
