package com.qf.miaosha.mapper;

import com.qf.miaosha.entity.TProduct;

public interface TProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Wed Apr 10 17:25:00 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Wed Apr 10 17:25:00 CST 2019
     */
    int insert(TProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Wed Apr 10 17:25:00 CST 2019
     */
    int insertSelective(TProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Wed Apr 10 17:25:00 CST 2019
     */
    TProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Wed Apr 10 17:25:00 CST 2019
     */
    int updateByPrimaryKeySelective(TProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Wed Apr 10 17:25:00 CST 2019
     */
    int updateByPrimaryKey(TProduct record);

    Integer getStoreById(Long id);

    void updateStoreById(Long id);
}